name: Go
on:
  workflow_call:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v3

      - id: auth
        uses: google-github-actions/auth@v1.1.0
        with:
          workload_identity_provider: "projects/852340051888/locations/global/workloadIdentityPools/github-deploy/providers/github-deploy"
          service_account: "howsmyssl-deploy@personal-sites-1295.iam.gserviceaccount.com"
          create_credentials_file: true

      - id: get-gke-credentials
        uses: google-github-actions/get-gke-credentials@v1.0.1
        with:
          cluster_name: dg
          location: us-central1-c

      - id: update-label
        run: kubectl -n prod label --overwrite deploy howsmyssl lookatme="${GITHUB_SHA}-${GITHUB_RUN_NUMBER}"

      - id: gcloud-config-docker
        run: gcloud auth configure-docker -q gcr.io

      - id: docker-build
        run: docker build -t gcr.io/personal-sites-1295/howsmyssl:${GITHUB_SHA} .

      - id: docker-push
        run: docker push gcr.io/personal-sites-1295/howsmyssl:${GITHUB_SHA}

      - id: get-deploys
        run: kubectl -n prod get deploy
