name: Go
on:
  workflow_call:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v3

      - id: auth
        uses: google-github-actions/auth@v1.1.0
        with:
          workload_identity_provider: "projects/852340051888/locations/global/workloadIdentityPools/github-deploy/providers/github-deploy"
          service_account: "howsmyssl-deploy@personal-sites-1295.iam.gserviceaccount.com"

      - id: "gcloud"
        name: "gcloud"
        run: |-
          gcloud services list

      - id: get-gke-credentials
        uses: google-github-actions/get-gke-credentials@v1.0.1
        with:
          cluster_name: dg
          location: us-central1-c

      - id: get-pods
        run: kubectl get pods
